# Generated by Django 4.2.13 on 2024-05-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='category_icons')),
                ('details', models.TextField()),
                ('positions', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('noOfEmployees', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='photos')),
                ('website', models.URLField()),
                ('overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_company', models.CharField(max_length=55)),
                ('job_salary', models.CharField(max_length=10)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=55)),
                ('job_category', models.CharField(max_length=55)),
                ('job_status', models.CharField(max_length=20)),
                ('job_experience_year', models.CharField(max_length=30)),
                ('job_qualification', models.TextField()),
                ('adminID', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userSocialMediaApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facbook_url', models.URLField(max_length=100, null=True)),
                ('linkiden_url', models.URLField(max_length=100, null=True)),
                ('twitter_url', models.URLField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='userSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=80)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='userResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoto', models.ImageField(blank=True, default='user-logo.png', null=True, upload_to='UPLOADEDIMAGES/')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='userGeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description_info', models.TextField(null=True)),
                ('user_current_position', models.CharField(max_length=80, null=True)),
                ('user_city_of_resideance', models.CharField(max_length=50, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='userExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_job_title', models.CharField(max_length=80)),
                ('experience_company', models.CharField(max_length=80)),
                ('experience_start_date', models.IntegerField()),
                ('experience_end_data', models.IntegerField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
        migrations.CreateModel(
            name='userEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_school', models.CharField(max_length=80)),
                ('education_degree', models.CharField(max_length=80)),
                ('education_start_year', models.IntegerField()),
                ('education_end_year', models.IntegerField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.users')),
            ],
        ),
    ]
