# Generated by Django 4.2.13 on 2024-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_userappliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='image',
            field=models.ImageField(default='OIP.jpg', upload_to='images/'),
        ),
    ]
